subinclude("///proto//build_defs/sdk")

proto_build_defs(
    name = "python",
    srcs = ["python.build_defs"],
    visibility = ["PUBLIC"],
    proto_languages = {
        "grpc_language": ["python_grpc_language"],
        "proto_language": ["python_proto_language"],
    }
)
