name: Python proto rules
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          python-version:
            - '3.9'
            - '3.10'
            - '3.11'
            - '3.12'
            - '3.13'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set profile
        run: export PLZ_CONFIG_PROFILE=ci && echo $PATH
      - name: Run tests
        run: ./pleasew test --log_file plz-out/log/test.log
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.python-version }}
          path: plz-out/log
  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/v1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: thought-machine/release-action@v0.3.0
